Feature/issue 333 CoR
deliveredtechnologies/terraform-maven pull request #181
Opened 2020-06-16 18:00 UTC by maganti07

2020-06-18 19:17 UTC, Clayton7510 commented on tf-build-tools/tf-cmd-api/src/main/java/com/deliveredtechnologies/terraform/terraformhandler/TerraformApplyS3Handler.java
> +      handleRequest(properties);
handleRequest shouldn't be in else; the chain will break if the condition is true. Is that really what you want? Only one request to be serviced by the chain?

2020-06-18 19:18 UTC, Clayton7510 commented on tf-build-tools/tf-cmd-api/src/main/java/com/deliveredtechnologies/terraform/terraformhandler/TerraformHandler.java
> +    if (nextHandlerAction != null) {
Consider using an Optional here. Null equality tests are not a great practice, in general.

2020-06-18 19:21 UTC, Clayton7510 commented on tf-build-tools/tf-cmd-api/src/main/java/com/deliveredtechnologies/terraform/terraformhandler/TerraformHandler.java
> +  public TerraformHandler nextHandlerAction(TerraformHandler nextHandlerAction) {
as a general rule, methods should be verbs; they are actions

2020-06-18 19:29 UTC, Clayton7510 commented on tf-build-tools/tf-cmd-api/src/main/java/com/deliveredtechnologies/terraform/terraformhandler/TerraformHandler.java
> +    return nextHandlerAction;
This is a Handler, not an action. doAction is the method implemented, but TerraformHandler is the type. The name is confusing - by the name one would assume that its of type HandlerAction. nextHandler would be a better name.

2020-06-18 19:29 UTC, Clayton7510 commented on tf-build-tools/tf-cmd-api/src/main/java/com/deliveredtechnologies/terraform/terraformhandler/TerraformHandler.java
> +      nextHandlerAction.doAction(properties);
The logic here is a little confusing. To initiate the chain, you call handleRequest, which in turn calls doAction on the next handler action (what about the current handler action?) and then the doAction implemented by the subclass is responsible for calling back to handleRequest?

Wouldn't it be simpler to abstract the execution of the action in the handler - and that's it. Then, the TerraformHandler handleRequest method is responsible for validating the next link in the chain, executing the action and moving to the next link in the chain?

Example:

```java
protected final void handleRequest(Properties properties) {
   doAction(properties);
   Optional.ofNullable(nextHandler).ifPresent(handler -> handler.handleRequest(properties));
}
```

2020-06-18 19:31 UTC, Clayton7510 commented on tf-build-tools/tf-cmd-api/src/main/java/com/deliveredtechnologies/terraform/terraformhandler/TerraformPlanS3Handler.java
> +      handleRequest(properties);
See the above comments. You are repeating yourself here. Think DRYer :)

2020-07-20 18:45 UTC, Clayton7510 commented on tf-build-tools/tf-cmd-api/src/main/java/com/deliveredtechnologies/terraform/terraformhandler/TerraformChainHandler.java
> +  private Executable executable;
I don't think you need this 'executable'

2020-07-20 18:48 UTC, Clayton7510 commented on tf-build-tools/tf-cmd-api/src/main/java/com/deliveredtechnologies/terraform/terraformhandler/TerraformChainHandler.java
> +public class TerraformChainHandler {
1. Javadocs - don't forget them ;)
2. Change the name of TerraformChainHandler to something the represents what it's used for
3. Dynamically create the chain (reflection); consider their may be pre-processing handlers and post-processing handlers

2020-07-20 18:48 UTC, Clayton7510 commented on tf-build-tools/tf-cmd-api/src/main/java/com/deliveredtechnologies/terraform/terraformhandler/TerraformChainHandler.java
> +  public void chainInitiator(Properties properties) throws IOException, TerraformException {
minor: methods should generally be verbs

2020-07-20 18:53 UTC, Clayton7510 commented on tf-build-tools/tf-cmd-api/src/main/java/com/deliveredtechnologies/terraform/terraformhandler/TerraformApplyS3Handler.java
> +package com.deliveredtechnologies.terraform.terraformhandler;
minor: redundant package name terraform/terraformhandler
consider terraform/handler

Something that you could do for pre-processing handlers is put them in a specific package, like terraform/handler/pre

2020-09-15 13:37 UTC, Clayton7510 commented
Checkstyle errors are failing the build :'(

2020-10-22 13:53 UTC, Clayton7510 requested changes
Some minor updates. But it looks pretty good.

2020-10-22 13:53 UTC, Clayton7510 commented on tf-build-tools/tf-cmd-api/src/main/java/com/deliveredtechnologies/terraform/handler/TerraformChainHandler.java
> +  public void chainInitiator(Properties properties) throws TerraformHandlerException {
Methods should be verbs. So, maybe runChain() or initiateChain()

2020-10-22 13:53 UTC, Clayton7510 commented on tf-build-tools/tf-cmd-api/src/main/java/com/deliveredtechnologies/terraform/handler/TerraformApplyS3Handler.java
> +
Javadocs? What's going on with the linting?

2020-10-22 13:53 UTC, Clayton7510 commented on tf-build-tools/tf-cmd-api/src/main/java/com/deliveredtechnologies/terraform/handler/TerraformApplyS3Handler.java
> +        e.printStackTrace();
This should be handled better - let's supply a better error message.

Maybe something like ```logger.error("Unable to get " + s3KeyName + "; " + e.getMessage());```

2020-10-22 13:53 UTC, Clayton7510 commented on tf-build-tools/tf-cmd-api/src/main/java/com/deliveredtechnologies/terraform/handler/TerraformPlanS3Handler.java
> +        e.printStackTrace();
Do not handle exceptions with printStackTrace(). Instead, if you want to handle the error by logging it, use the logger.

2020-10-22 13:53 UTC, Clayton7510 commented on tf-build-tools/tf-cmd-api/src/test/java/com/deliveredtechnologies/terraform/terraformhandler/TerraformHandlerTest.java
> +  public void executeHandlerWithDoAction() {
Two scenarios: 
1. nextHandler is present 
   set the next Handler
   call handleRequest
   validate that doAction was called on the current Handler
   validate that doAction was called on the next Handler
2. nextHandler is not present.
   set the next Handler
   call handleRequest
   validate that doAction was called on the current Handler

2020-11-03 21:00 UTC, Clayton7510 commented
Please remove the tfplan files from the PR.

2020-12-04 19:43 UTC, Clayton7510 approved these changes

2020-12-04 19:43 UTC, Clayton7510 commented on tf-build-tools/tf-cmd-api/src/main/java/com/deliveredtechnologies/terraform/handler/TerraformChainHandler.java
> +  String tfRootDir;
Why not are the instance variables package private?

2020-12-04 19:43 UTC, Clayton7510 commented on tf-build-tools/tf-cmd-api/src/main/java/com/deliveredtechnologies/terraform/handler/TerraformHandlerException.java
> +public class TerraformHandlerException extends Exception {
JavaDocs, pls

2020-12-17 18:29 UTC, palaniswamy commented
All good

2020-12-17 18:31 UTC, palaniswamy approved these changes
Approved

2020-12-17 18:33 UTC, merged